create or replace TABLE travel_data.ADMIN.TRANSFORMATION_LOGS (
    TRANSFORMATION_ID NUMBER IDENTITY(1,1) PRIMARY KEY,
    LOAD_ID NUMBER,
    DATASET_NAME VARCHAR(100),
    TARGET_TABLE VARCHAR(100),
    STATUS VARCHAR(20),
    ROWS_PROCESSED NUMBER,
    ERROR_MESSAGE STRING,
    START_TIME TIMESTAMP_NTZ(9),
    END_TIME TIMESTAMP_NTZ(9)
);