DROP SCHEMA IF EXISTS ADMIN CASCADE;
DROP SCHEMA IF EXISTS BRONZE CASCADE;
DROP SCHEMA IF EXISTS SILVER CASCADE;
DROP SCHEMA IF EXISTS GOLD CASCADE;

CREATE SCHEMA ADMIN;
CREATE SCHEMA BRONZE;
CREATE SCHEMA SILVER;
CREATE SCHEMA GOLD;

CREATE TABLE IF NOT EXISTS ADMIN.INGESTION_LOGS (
    LOAD_ID NUMBER IDENTITY(1,1) PRIMARY KEY,
    DATASET_NAME VARCHAR(50),
    FILE_NAME VARCHAR(255),
    FILE_SIZE_BYTES NUMBER,
    FILE_TYPE VARCHAR(20),
    ROW_COUNT NUMBER,
    STATUS VARCHAR(20),
    ERROR_MESSAGE STRING,
    INGESTION_TIMESTAMP TIMESTAMP_NTZ(9),
    TARGET_SCHEMA VARCHAR(50),
    TARGET_TABLE VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS ADMIN.TRANSFORMATION_LOGS (
    TRANSFORMATION_ID NUMBER IDENTITY(1,1) PRIMARY KEY,
    LOAD_ID NUMBER,
    TRANSFORMATION_NAME VARCHAR(100),
    TARGET_TABLE VARCHAR(100),
    STATUS VARCHAR(20),
    ROWS_PROCESSED NUMBER,
    ERROR_MESSAGE STRING,
    START_TIME TIMESTAMP_NTZ(9),
    END_TIME TIMESTAMP_NTZ(9)
);