create or replace TABLE TRAVEL_DATA.SILVER.HEART_RATE_MINUTE_LOG (
	LOG_TIMESTAMP VARCHAR(16777216),
	LOAD_ID NUMBER(38,0),
	HEART_RATE_MEAN FLOAT,
	HEART_RATE_MIN FLOAT,
	HEART_RATE_MAX FLOAT,
	READINGS_COUNT NUMBER(38,0),
	HR_ZONE VARCHAR(16777216)
);