create or replace TABLE TRAVEL_DATA.SILVER.GOOGLE_TIMELINE (
	TIMELINE_ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	LOAD_ID NUMBER(38,0),
	START_TIME TIMESTAMP_NTZ(9),
	END_TIME TIMESTAMP_NTZ(9),
	SEGMENT_TYPE VARCHAR(50),
	PLACE_ID VARCHAR(255),
	VISIT_LATITUDE NUMBER(10,7),
	VISIT_LONGITUDE NUMBER(10,7),
	ACTIVITY_TYPE VARCHAR(100),
	ACTIVITY_START_LATITUDE NUMBER(10,7),
	ACTIVITY_START_LONGITUDE NUMBER(10,7),
	ACTIVITY_END_LATITUDE NUMBER(10,7),
	ACTIVITY_END_LONGITUDE NUMBER(10,7),
	DISTANCE_METERS NUMBER(10,2),
	CONFIDENCE NUMBER(5,4),
	primary key (TIMELINE_ID)
);