create or replace TABLE TRAVEL_DATA.SILVER.HEART_RATE_HOURLY_SUMMARY (
	DATE VARCHAR(16777216),
	HOUR NUMBER(38,0),
	LOAD_ID NUMBER(38,0),
	HOURLY_AVG_HR FLOAT,
	HOURLY_MIN_HR FLOAT,
	HOURLY_MAX_HR FLOAT,
	MINUTES_IN_RESTING NUMBER(38,0),
	MINUTES_IN_ELEVATED NUMBER(38,0),
	MINUTES_IN_HIGH NUMBER(38,0)
);