CREATE OR REPLACE PROCEDURE TRAVEL_DATA.GOLD.SP_TRAVEL_TAX_REPORT()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
    -- 1. Create the GOLD table if it doesn''t exist
    CREATE TABLE IF NOT EXISTS TRAVEL_DATA.GOLD.TRAVEL_TAX_REPORT (
        REPORT_DATE DATE,
        IS_TRAVEL_DAY BOOLEAN,
        TOTAL_FLIGHT_HOURS FLOAT,
        FLIGHT_COUNT INT,
        DESTINATION_CITY VARCHAR(16777216),
        NEXT_DAY_SLEEP_SCORE INT,
        NEXT_DAY_DEEP_SLEEP_MIN INT,
        NEXT_DAY_RESTING_HR INT,
        NEXT_DAY_HR_VARIABILITY FLOAT, 
        RECOVERY_STATUS VARCHAR(50)
    );

    -- 2. Truncate the Gold Table
    TRUNCATE TABLE TRAVEL_DATA.GOLD.TRAVEL_TAX_REPORT;

    -- 3. Insert Logic
    INSERT INTO TRAVEL_DATA.GOLD.TRAVEL_TAX_REPORT
    WITH 
    -- STEP A: Clean Flight Logs
    CLEAN_FLIGHTS AS (
        SELECT 
            TO_DATE(DATE) AS FLIGHT_DATE,
            "TO" AS ARRIVAL_AIRPORT,
            TRY_TO_TIME(DURATION) AS DURATION_TIME,
            (HOUR(TRY_TO_TIME(DURATION)) + MINUTE(TRY_TO_TIME(DURATION))/60.0) AS DURATION_HOURS
        FROM TRAVEL_DATA.SILVER.FLIGHT_LOGS
        QUALIFY ROW_NUMBER() OVER (PARTITION BY DATE, FLIGHT_NUMBER ORDER BY LOAD_ID DESC) = 1
    ),
    
    -- STEP B: Aggregate Flights to Daily
    DAILY_FLIGHTS AS (
        SELECT 
            FLIGHT_DATE,
            SUM(DURATION_HOURS) AS TOTAL_FLIGHT_HOURS,
            COUNT(*) AS FLIGHT_COUNT,
            LISTAGG(DISTINCT ARRIVAL_AIRPORT, '', '') AS DESTINATIONS
        FROM CLEAN_FLIGHTS
        GROUP BY FLIGHT_DATE
    ),

    -- STEP C: Clean Sleep Logs
    CLEAN_SLEEP AS (
        SELECT 
            TO_DATE(TIMESTAMP) AS WAKE_UP_DATE, 
            OVERALL_SCORE,
            DEEP_SLEEP_IN_MINUTES,
            RESTING_HEART_RATE
        FROM TRAVEL_DATA.SILVER.SLEEP_LOG
        QUALIFY ROW_NUMBER() OVER (PARTITION BY SLEEP_LOG_ENTRY_ID ORDER BY LOAD_ID DESC) = 1
    ),

    -- STEP D1: Deduplicate Heart Rate (Hourly Level First)
    HR_DEDUP AS (
        SELECT 
            DATE,
            HOUR,
            HOURLY_MIN_HR,
            HOURLY_MAX_HR,
            HOURLY_AVG_HR
        FROM TRAVEL_DATA.SILVER.HEART_RATE_HOURLY_SUMMARY
        QUALIFY ROW_NUMBER() OVER (PARTITION BY DATE, HOUR ORDER BY LOAD_ID DESC) = 1
    ),

    -- STEP D2: Aggregate Heart Rate (Daily Level Second)
    DAILY_HR AS (
        SELECT 
            TO_DATE(DATE) AS HR_DATE,
            MIN(HOURLY_MIN_HR) AS DAILY_MIN_HR,
            MAX(HOURLY_MAX_HR) AS DAILY_MAX_HR,
            AVG(HOURLY_AVG_HR) AS DAILY_AVG_HR
        FROM HR_DEDUP
        GROUP BY TO_DATE(DATE)
    )

    SELECT 
        -- Base Date (The Travel Day)
        COALESCE(F.FLIGHT_DATE, S.WAKE_UP_DATE - 1) AS REPORT_DATE,
        
        -- Flag if this was a travel day
        CASE WHEN F.TOTAL_FLIGHT_HOURS > 0 THEN TRUE ELSE FALSE END AS IS_TRAVEL_DAY,
        
        -- Flight Metrics
        ZEROIFNULL(F.TOTAL_FLIGHT_HOURS) AS TOTAL_FLIGHT_HOURS,
        ZEROIFNULL(F.FLIGHT_COUNT) AS FLIGHT_COUNT,
        COALESCE(F.DESTINATIONS, ''No Travel'') AS DESTINATION_CITY,

        -- Recovery Metrics (Joined on REPORT_DATE + 1 day)
        S.OVERALL_SCORE AS NEXT_DAY_SLEEP_SCORE,
        S.DEEP_SLEEP_IN_MINUTES AS NEXT_DAY_DEEP_SLEEP_MIN,
        S.RESTING_HEART_RATE AS NEXT_DAY_RESTING_HR,
        
        -- HR Variability proxy
        (H.DAILY_MAX_HR - H.DAILY_MIN_HR) AS NEXT_DAY_HR_VARIABILITY,

        -- Calculated Status
        CASE 
            WHEN F.TOTAL_FLIGHT_HOURS > 4 AND S.OVERALL_SCORE < 70 THEN ''High Strain''
            WHEN S.OVERALL_SCORE > 85 THEN ''Well Recovered''
            ELSE ''Normal''
        END AS RECOVERY_STATUS

    FROM DAILY_FLIGHTS F
    FULL OUTER JOIN CLEAN_SLEEP S 
        ON F.FLIGHT_DATE = (S.WAKE_UP_DATE - 1) 
    LEFT JOIN DAILY_HR H
        ON (S.WAKE_UP_DATE) = H.HR_DATE;

    RETURN ''SUCCESS: Gold table TRAVEL_TAX_REPORT rebuilt.'';
END;
';